diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=D:/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=rifqiadiyatma
user.email=93rifqiadiyatma@gmail.com
core.editor="F:\Microsoft VS Code\Code.exe" --wait
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.areti.url=https://github.com/rifqiadiyatma/areti.git
remote.areti.fetch=+refs/heads/*:refs/remotes/areti/*
remote.origin.url=git@github.com:rifqiadiyatma/areti.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
